Repository openshift/node-observability-agent, pull requests merged in 2022-03, with the labels that each got.

#1 First version
  Dockerfile
  Dockerfile_allShell
  Makefile
  README.md
  cmd/node-observability-agent.go
  go.mod
  go.sum
  hack/collect-proflie-data.sh
  pkg/handlers/crioProfilingHandler.go
  pkg/handlers/handlers.go
  pkg/handlers/kubeletProfilingHandler.go
  pkg/server/routes.go
  pkg/server/server.go
  scripts/profile-crio.sh
  scripts/profile-kubelet.sh
  scripts/sleep.sh
  test_resources/go-agent-ds.yaml
  test_resources/go-agent-srv.yaml
  test_resources/ubi-clusterrole.yaml
  test_resources/ubi-crio.yaml
  test_resources/ubi-kubelet.yaml
  test_resources/ubi-mc.yaml
  test_resources/ubi-pvc.yaml
  test_resources/ubi-role.yaml
  test_resources/ubi-scc.yaml
Labels: lgtm

#2 Add OWNERS
  OWNERS
Labels: do-not-merge/invalid-owners-file

#8 Kustomize manifests
  README.md
  test_resources/default/daemonset.yaml
  test_resources/default/daemonset_patch.yaml
  test_resources/default/kustomization.yaml
  test_resources/default/kustomizeconfig/serviceaccount.yaml
  test_resources/default/machine_config.yaml
  test_resources/default/pvc.yaml
  test_resources/default/pvc_patch.yaml
  test_resources/default/rbac.yaml
  test_resources/default/sa.yaml
  test_resources/default/scc.yaml
  test_resources/default/service.yaml
  test_resources/ubi-clusterrole.yaml
  test_resources/ubi-crio.yaml
  test_resources/ubi-kubelet.yaml
  test_resources/ubi-role.yaml
Labels: lgtm, approved

#9 Add unit test for profilingHandlers
  Makefile
  cmd/node-observability-agent.go
  go.mod
  pkg/connectors/MockCmdWrapper.go
  pkg/connectors/cmdWrapper.go
  pkg/handlers/crioProfilingHandler.go
  pkg/handlers/crioProfilingHandler_test.go
  pkg/handlers/handlers.go
  pkg/handlers/kubeletProfilingHandler.go
  pkg/handlers/kubeletProfilingHandler_test.go
  pkg/server/routes.go
Labels: lgtm, approved

#14 go.mod fix format 1.17
  go.mod
Labels: lgtm, approved

#12 CFE-250 - Fix linting issues
  Makefile
  cmd/node-observability-agent/main.go
  pkg/connectors/MockCmdWrapper.go
  pkg/connectors/cmdWrapper.go
  pkg/handlers/crioProfilingHandler.go
  pkg/handlers/crioProfilingHandler_test.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/kubeletProfilingHandler.go
  pkg/handlers/kubeletProfilingHandler_test.go
  pkg/server/routes.go
  pkg/server/server.go
Labels: lgtm, approved

#17 Fix create project in OCP only if it doesnt exist
  Makefile
Labels: lgtm, approved

#16 Reinforce locking mecanism around profiling requests
  pkg/handlers/crioProfilingHandler.go
  pkg/handlers/crioProfilingHandler_test.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/kubeletProfilingHandler.go
  pkg/handlers/kubeletProfilingHandler_test.go
  pkg/runs/run.go
  pkg/statelocker/statelocker.go
  pkg/statelocker/statelocker_test.go
Labels: lgtm, approved

#19 Security audit mitigation updates
  cmd/node-observability-agent/main.go
  cover.html
  pkg/handlers/kubeletProfilingHandler.go
  pkg/handlers/kubeletProfilingHandler_test.go
  pkg/statelocker/statelocker.go
Labels: lgtm, approved
